
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:

- job: unittests

  strategy:
    matrix:
      python35:
        python.version: '3.5'
      python36:
        python.version: '3.6'
      python37:
        python.version: '3.7'
      python38:
        python.version: '3.8'

  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  # - script: pip install -e .
    # displayName: "Install module"

  - script: pip install -e ".[tests]"
    displayName: "Install test dependencies"

  - script: python3 run_tests.py
    displayName: "Run tests"